FROM python:3

WORKDIR /app/Server
COPY Server/tcp_server.py .
COPY common /app/common

WORKDIR /app/Server

RUN apt update
RUN apt install tcpdump -y

ENV PYTHONPATH=/app/common:$PYTHONPATH
ENTRYPOINT ["python3", "tcp_server.py"]

